proyectoDjango/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from appDjango.views import mostrar_familiares, BuscarFamiliar, ActualizarFamiliar, AltaFamiliar, BorrarFamiliar, mostrar_mascotas, AltaMascota, ActualizarMascota, BuscarMascota, BorrarMascota, mostrar_vehiculos, BuscarVehiculo, AltaVehiculo, ActualizarVehiculo, BorrarVehiculo
from appBlog.views import index, PostList, PostCrear, PostActualizar, PostBorrar, PostDetalle, UserSignUp, UserLogin, UserLogOut, AvatarActualizar, UserActualizar, aboutme
from django.contrib.admin.views.decorators import staff_member_required


urlpatterns = [
    path('admin/', admin.site.urls),
    path('appBlog/', index, name="appBlog-index"),
    path('appBlog/listar/', PostList.as_view(), name="appBlog-listar"),
    path('appBlog/crear/', PostCrear.as_view(), name="appBlog-crear"),
    path('appBlog/<int:pk>/actualizar/', PostActualizar.as_view(), name="appBlog-actualizar"),
    path('appBlog/<int:pk>/borrar/', PostBorrar.as_view(), name="appBlog-borrar"),
    path('appBlog/<int:pk>/detalle/', PostDetalle.as_view(), name="appBlog-detalle"),
    path('appBlog/registro', UserSignUp.as_view(), name="appBlog-registro"),
    path('appBlog/ingresar', UserLogin.as_view(), name="appBlog-ingresar"),
    path('appBlog/salir', UserLogOut.as_view(), name="appBlog-salir"),
    path('appBlog/avatar/<int:pk>/actualizar/', AvatarActualizar.as_view(), name="appBlog-avatar-actualizar"),
    path('appBlog/users/<int:pk>/actualizar/', UserActualizar.as_view(), name="appBlog-user-actualizar"),
    path('appBlog/acerca-de-mi', aboutme, name="appBlog-acerca-de-mi")
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

appDjango/models.py
from django.db import models

class Familiar(models.Model):
    nombre = models.CharField(max_length=100)
    fecha_de_nacimiento = models.CharField(max_length=200)
    dni = models.IntegerField()
    def __str__(self):
      return f"{self.nombre}, {self.fecha_de_nacimiento}, {self.dni}"
    
class Mascota(models.Model):
    nombre = models.CharField(max_length=50)
    edad = models.IntegerField()
    animal = models.CharField(max_length=50)
    def __str__(self):
      return f"{self.nombre}, {self.edad}, {self.animal}"
    
class Vehiculo(models.Model):
    tipo = models.CharField(max_length=50)
    antiguedad = models.IntegerField()
    marca = models.CharField(max_length=50)

appDjango/forms.py
from django import forms
from appDjango.models import Familiar, Mascota, Vehiculo

class Buscar(forms.Form):
    nombre = forms.CharField(max_length=100)
    
class BuscarVehiculo(forms.Form):
    marca = forms.CharField(max_length=100)

class FamiliarForm(forms.ModelForm):
  class Meta:
    model = Familiar
    fields = ['nombre', 'dni', 'fecha_de_nacimiento']   
    
class MascotaForm(forms.ModelForm):
  class Meta:
    model = Mascota
    fields = ['nombre', 'edad', 'animal']   
    
class VehiculoForm(forms.ModelForm):
  class Meta:
    model = Vehiculo
    fields = ['tipo', 'antiguedad', 'marca']   
    

appDjango/views.py
from django.shortcuts import render, get_object_or_404
from appDjango.models import Familiar, Mascota, Vehiculo
from appDjango.forms import Buscar, FamiliarForm, MascotaForm, VehiculoForm,BuscarVehiculo # <--- NUEVO IMPORT
from django.views import View # <-- NUEVO IMPORT 
from django import forms
# Create your views here.


#------------------------------------FAMILIAR-----------------------------

def mostrar_familiares(request):
  lista_familiares = Familiar.objects.all()
  return render(request, "appDjango/mi-familia.html", {"lista_familiares": lista_familiares})

class BuscarFamiliar(View):
    form_class = Buscar
    template_name = 'appDjango/buscarFamiliar.html'
    initial = {"nombre":""}
    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form})
    def post(self, request):
        form = self.form_class(request.POST)
        msg_error = f"No se encontro el familiar"
        if form.is_valid():
            nombre = form.cleaned_data.get("nombre")
            lista_familiares = Familiar.objects.filter(nombre__icontains=nombre).all()
            form = self.form_class(initial=self.initial)
            return render(request, self.template_name, {'form':form, 
                                                        'lista_familiares':lista_familiares})
        return render(request, self.template_name, {"form": form})
    
class AltaFamiliar(View):

    form_class = FamiliarForm
    template_name = 'appDjango/altaFamiliar.html'
    initial = {"nombre":"", "dni":"", "fecha_de_nacimiento":""}

    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            msg_exito = f"se cargo con éxito el familiar {form.cleaned_data.get('nombre')}"
            form = self.form_class(initial=self.initial)
            return render(request, self.template_name, {'form':form, 
                                                        'msg_exito': msg_exito})
        
        return render(request, self.template_name, {"form": form})    



class ActualizarFamiliar(View):
  form_class = FamiliarForm
  template_name = 'appDjango/actualizarFamiliar.html'
  initial = {"nombre":"", "dni":"", "fecha_de_nacimiento":""}
  
  def get(self, request, pk): 
      familiar = get_object_or_404(Familiar, pk=pk)
      form = self.form_class(instance=familiar)
      return render(request, self.template_name, {'form':form,'familiar': familiar})

  def post(self, request, pk): 
      familiar = get_object_or_404(Familiar, pk=pk)
      form = self.form_class(request.POST ,instance=familiar)
      if form.is_valid():
          form.save()
          msg_exito = f"se actualizó con éxito el familiar {form.cleaned_data.get('nombre')}"
          form = self.form_class(initial=self.initial)
          return render(request, self.template_name, {'form':form, 
                                                      'familiar': familiar,
                                                      'msg_exito': msg_exito})
      
      return render(request, self.template_name, {"form": form})
  
class BorrarFamiliar(View):
  template_name = 'appDjango/mi-familia.html'

  def get(self, request, pk): 
      familiar = get_object_or_404(Familiar, pk=pk)
      familiar.delete()
      familiares = Familiar.objects.all()
      return render(request, self.template_name, {'lista_familiares': familiares})

#------------------------------MASCOTA--------------------------------

def mostrar_mascotas(request):
  lista_mascotas = Mascota.objects.all()
  return render(request, "appDjango/mis-mascotas.html", {"lista_mascotas": lista_mascotas})

class AltaMascota(View):

    form_class = MascotaForm
    template_name = 'appDjango/altaMascota.html'
    initial = {"nombre":"", "edad":"", "animal":""}

    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            msg_exito = f"se cargo con éxito la mascota {form.cleaned_data.get('nombre')}"
            form = self.form_class(initial=self.initial)
            return render(request, self.template_name, {'form':form, 
                                                        'msg_exito': msg_exito})
        
        return render(request, self.template_name, {"form": form})    
    
class ActualizarMascota(View):
  form_class = MascotaForm
  template_name = 'appDjango/actualizarMascota.html'
  initial = {"nombre":"", "edad":"", "animal":""}
  
  def get(self, request, pk): 
      mascota = get_object_or_404(Mascota, pk=pk)
      form = self.form_class(instance=mascota)
      return render(request, self.template_name, {'form':form,'mascota': mascota})

  def post(self, request, pk): 
      mascota = get_object_or_404(Mascota, pk=pk)
      form = self.form_class(request.POST ,instance=mascota)
      if form.is_valid():
          form.save()
          msg_exito = f"se actualizó con éxito el familiar {form.cleaned_data.get('nombre')}"
          form = self.form_class(initial=self.initial)
          return render(request, self.template_name, {'form':form, 
                                                      'mascota': mascota,
                                                      'msg_exito': msg_exito})
      
      return render(request, self.template_name, {"form": form})

class BorrarMascota(View):
  template_name = 'appDjango/mis-mascotas.html'

  def get(self, request, pk): 
      mascota = get_object_or_404(Mascota, pk=pk)
      mascota.delete()
      mascotas = Mascota.objects.all()
      return render(request, self.template_name, {'lista_mascotas': mascotas})


class BuscarMascota(View):
    form_class = Buscar
    template_name = 'appDjango/buscarMascota.html'
    initial = {"nombre":""}
    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form})
    def post(self, request):
        form = self.form_class(request.POST)
        msg_error = f"No se encontro la mascota"
        if form.is_valid():
            nombre = form.cleaned_data.get("nombre")
            lista_mascotas = Mascota.objects.filter(nombre__icontains=nombre).all()
            form = self.form_class(initial=self.initial)
            return render(request, self.template_name, {'form':form, 
                                                        'lista_mascotas':lista_mascotas})
        return render(request, self.template_name, {"form": form})

#---------------------------- VEHICULO -----------------------------------------

def mostrar_vehiculos(request):
  lista_vehiculos = Vehiculo.objects.all()
  return render(request, "appDjango/vehiculos.html", {"lista_vehiculos": lista_vehiculos})

class BuscarVehiculo(View):
    form_class = BuscarVehiculo
    template_name = 'appDjango/buscarVehiculo.html'
    initial = {"marca":""}
    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form})
    def post(self, request):
        form = self.form_class(request.POST)
        msg_error = f"No se encontro el Vehiculo"
        if form.is_valid():
            marca = form.cleaned_data.get("marca")
            lista_vehiculos = Vehiculo.objects.filter(marca__icontains=marca).all()
            form = self.form_class(initial=self.initial)
            return render(request, self.template_name, {'form':form, 
                                                        'lista_vehiculos':lista_vehiculos})
        return render(request, self.template_name, {"form": form})
    
class AltaVehiculo(View):

    form_class = VehiculoForm
    template_name = 'appDjango/altaVehiculo.html'
    initial = {"tipo":"", "antiguedad":"", "marca":""}

    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            msg_exito = f"se cargo con éxito el Vehiculo {form.cleaned_data.get('marca')}"
            form = self.form_class(initial=self.initial)
            return render(request, self.template_name, {'form':form, 
                                                        'msg_exito': msg_exito})
        
        return render(request, self.template_name, {"form": form})   
    
class ActualizarVehiculo(View):
  form_class = VehiculoForm
  template_name = 'appDjango/actualizarVehiculo.html'
  initial = {"tipo":"", "antiguedad":"", "animal":""}
  
  def get(self, request, pk): 
      vehiculo = get_object_or_404(Vehiculo, pk=pk)
      form = self.form_class(instance=vehiculo)
      return render(request, self.template_name, {'form':form,'vehiculo': vehiculo})

  def post(self, request, pk): 
      vehiculo = get_object_or_404(Vehiculo, pk=pk)
      form = self.form_class(request.POST ,instance=vehiculo)
      if form.is_valid():
          form.save()
          msg_exito = f"se actualizó con éxito el Vehiculo {form.cleaned_data.get('marca')}"
          form = self.form_class(initial=self.initial)
          return render(request, self.template_name, {'form':form, 
                                                      'vehiculo': vehiculo,
                                                      'msg_exito': msg_exito})
      
      return render(request, self.template_name, {"form": form})
  
class BorrarVehiculo(View):
  template_name = 'appDjango/vehiculos.html'

  def get(self, request, pk): 
      vehiculo = get_object_or_404(Vehiculo, pk=pk)
      vehiculo.delete()

appDjango/templates/appDjango/actualizarFamiliar.html
{% extends 'appDjango/base.html' %}
{% block titulo %}Actualizar Familiar{% endblock %}
{% block contenido %}
            <div class="main__contenedor-principal__botones">
                <form action="/mi-familia/actualizar/{{ familiar.id }}" method="post"> 
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Enviar" id="boton-enviar">
                </form>
                <h2 style="color:green">{{msg_exito}}</h2>
                <a href="/mi-familia/" id="boton-volver">Volver a la lista de familiares</a>
            </div>
        </div>
    </main>
{% endblock %}

appDjango/templates/appDjango/actualizarMascota.html
{% extends 'appDjango/base.html' %}
{% block titulo %}Actualizar Mascotas{% endblock %}
{% block contenido %}
            <div class="main__contenedor-principal__botones">
                <form action="/mis-mascotas/actualizar/{{ mascota.id }}" method="post"> 
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Enviar" id="boton-enviar">
                </form>
                <h2 style="color:green">{{msg_exito}}</h2>
                <a href="/mis-mascotas/" id="boton-volver">Volver a la lista de mascotas</a>
            </div>
        </div>
    </main>
{% endblock %}

appDjango/templates/appDjango/actualizarVehiculo.html
{% extends 'appDjango/base.html' %}
{% block titulo %}Actualizar Vehiculo{% endblock %}
{% block contenido %}
            <div class="main__contenedor-principal__botones">
                <form action="/vehiculos/actualizar/{{ vehiculo.id }}" method="post"> 
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Enviar" id="boton-enviar">
                </form>
                <h2 style="color:green">{{msg_exito}}</h2>
                <a href="/vehiculos/" id="boton-volver">Volver a la lista de vehiculos</a>
            </div>
        </div>
    </main>
{% endblock %}

appDjango/templates/appDjango/altaFamiliar.html
{% extends 'appDjango/base.html' %}
{% block titulo %}Crear Familiar{% endblock %}
{% block contenido %}
            <div class="main__contenedor-principal__botones">    
                <form action="/mi-familia/alta" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Enviar" id="boton-enviar">
                </form>
                <p style="color:green">{{msg_exito}}</p>
                <a href="/mi-familia/"><h2>Volver a mi familia</h2></a>
            </div>
{% endblock %}

appDjango/templates/appDjango/altaMascota.html
{% extends 'appDjango/base.html' %}
{% block titulo %}Crear Mascota{% endblock %}
{% block contenido %}
<div class="main__contenedor-principal__botones">    
    <form action="/mis-mascotas/alta" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Enviar" id="boton-enviar">
    </form>
    <p style="color:green">{{msg_exito}}</p>
    <a href="/mis-mascotas/" id="boton-volver">Volver a la lista de mascotas</a>
</div>
{% endblock %}

appDjango/templates/appDjango/altaVehiculo.html
{% extends 'appDjango/base.html' %}
{% block titulo %}Crear Vehiculo{% endblock %}
{% block contenido %}
<div class="main__contenedor-principal__botones">    
    <form action="/vehiculos/alta" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Enviar" id="boton-enviar">
    </form>
    <p style="color:green">{{msg_exito}}</p>
    <a href="/vehiculos/" id="boton-volver">Volver a la lista de vehiculos</a>
</div>
{% endblock %}

appDjango/templates/appDjango/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Document</title>
</head>

<body>
    <main>
        <div class="main__contenedor-principal">
            <div class="main__contenedor-principal__titulo">
                <h1>{% block titulo %}{% endblock %}</h1>
            </div>
            {% block contenido %}{% endblock %}
        </div>
    </main>
</body>

</html>

appDjango/templates/appDjango/buscarFamiliar.html
{% extends 'appDjango/base.html' %}
{% block titulo %}Buscador de Familiar{% endblock %}
{% block contenido %}
        <div class="main__contenedor-principal__botones">
            <form action="/mi-familia/buscarFamiliar" method="post">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Enviar" id="boton-enviar">
            </form>
        </div>
        <div class="main__contenedor-principal__lista" >
            {% for familiar in lista_familiares %}
                <ul>
                    <li class="animate__animated animate__flipInX"> Nombre: {{familiar.nombre}}, DNI: {{familiar.dni}}, Fecha de Nacimiento: {{familiar.fecha_de_nacimiento}}
                    </li>
                    <a href='/mi-familia/actualizar/{{ familiar.id }}'>{% load static %}<img src="{% static 'edit.png' %}" alt=""></a>
                    <a href='/mi-familia/borrar/{{ familiar.id }}'>{% load static %}<img src="{% static 'delete.png' %}" alt=""></a>
                </ul>
            {% endfor %}
        </div>
{% endblock %}

appDjango/templates/appDjango/buscarMascota.html
{% extends 'appDjango/base.html' %}
{% block titulo %}Buscador de Mascota{% endblock %}
{% block contenido %}
        <div class="main__contenedor-principal__botones">
            <form action="/mis-mascotas/buscarMascota" method="post">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Enviar" id="boton-enviar">
            </form>
        </div>
        <div class="main__contenedor-principal__lista" >
            {% for mascota in lista_mascotas %}
                <ul>
                    <li class="animate__animated animate__flipInX"> Nombre: {{mascota.nombre}}, Edad: {{mascota.edad}}, Animal: {{mascota.animal}} 
                    </li>
                    <a href='/mis-mascotas/actualizar/{{ mascota.id }}'>{% load static %}<img src="{% static 'edit.png' %}" alt=""></a>
                    <a href='/mis-mascotas/borrar/{{ mascota.id }}'>{% load static %}<img src="{% static 'delete.png' %}" alt=""></a>
                </ul>
            {% endfor %}
        </div>
{% endblock %}

appDjango/templates/appDjango/buscarVehiculo.html
{% extends 'appDjango/base.html' %}
{% block titulo %}Buscador de Vehiculo{% endblock %}
{% block contenido %}
        <div class="main__contenedor-principal__botones">
            <form action="/vehiculos/buscarVehiculo" method="post">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Enviar" id="boton-enviar">
            </form>
        </div>
        <div class="main__contenedor-principal__lista" >
            {% for vehiculo in lista_vehiculos %}
                <ul>
                    <li class="animate__animated animate__flipInX"> Tipo: {{vehiculo.tipo}}, Antiguedad: {{vehiculo.antiguedad}}, Marca: {{vehiculo.marca}}
                    </li>
                    <a href='/vehiculos/actualizar/{{ vehiculo.id }}'>{% load static %}<img src="{% static 'edit.png' %}" alt=""></a>
                    <a href='/vehiculos/borrar/{{ vehiculo.id }}'>{% load static %}<img src="{% static 'delete.png' %}" alt=""></a>
                </ul>
            {% endfor %}
        </div>
{% endblock %}

appDjango/templates/appDjango/mi-familia.html
{% extends 'appDjango/base.html' %}
{% block titulo %}Lista de Familiares{% endblock %}
{% block contenido %}
            <div class="main__contenedor-principal__botones">
                <form action="/mi-familia/buscarFamiliar" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <label for="id_nombre">Nombre:</label>
                    <input type="text" placeholder="Ingrese el familiar a buscar..."required id="id_nombre" name="nombre" maxlength="100">
                    <input type="submit" value="Enviar" id="boton-enviar">
                </form>    
            </div>
            <a href="/mi-familia/alta" id="boton-alta">Crear Familiar</a>
            <div class="main__contenedor-principal__lista">
                {% for familiar in lista_familiares %}
                    <ul>
                        <li class="animate__animated animate__flipInX"> Nombre: {{familiar.nombre}}, DNI: {{familiar.dni}}, Fecha de Nacimiento: {{familiar.fecha_de_nacimiento}} 
                        </li>
                        <a href='/mi-familia/actualizar/{{ familiar.id }}'>{% load static %}<img src="{% static 'edit.png' %}" alt=""></a>
                        <a href='/mi-familia/borrar/{{ familiar.id }}'>{% load static %}<img src="{% static 'delete.png' %}" alt=""></a>
                    </ul>
                {% endfor %}
            </div>
            {% endblock %}

appDjango/templates/appDjango/mis-mascotas.html
{% extends 'appDjango/base.html' %}
{% block titulo %}Lista de Mascotas{% endblock %}
{% block contenido %}
<div class="main__contenedor-principal__botones">
    <form action="/mis-mascotas/buscarMascota" method="post">
        {% csrf_token %}
        {{ form }}
        <label for="id_nombre">Nombre:</label>
        <input type="text" placeholder="Ingrese el familiar a buscar..."required id="id_nombre" name="nombre" maxlength="100">
        <input type="submit" value="Enviar" id="boton-enviar">
    </form>
</div>
<a href="/mis-mascotas/alta" id="boton-alta">Crear Mascota</a>
<div class="main__contenedor-principal__lista">
    {% for mascota in lista_mascotas %}
        <ul>
            <li class="animate__animated animate__flipInX"> Nombre: {{mascota.nombre}}, Edad: {{mascota.edad}}, Animal: {{mascota.animal}}</li> 
            <a href='/mis-mascotas/actualizar/{{ mascota.id }}'>{% load static %}<img src="{% static 'edit.png' %}" alt=""></a>
            <a href='/mis-mascotas/borrar/{{ mascota.id }}'>{% load static %}<img src="{% static 'delete.png' %}" alt=""></a>

        </ul>
    {% endfor %}
</div>
{% endblock %}

appDjango/templates/appDjango/vehiculos.html
{% extends 'appDjango/base.html' %}
{% block titulo %}Lista de Vehiculos{% endblock %}
{% block contenido %}  
            <div class="main__contenedor-principal__botones">
                <form action="/vehiculos/buscarVehiculo" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <label for="id_marca">Marca:</label>
                    <input type="text" placeholder="Ingrese el vehiculo a buscar..."required id="id_marca" name="marca" maxlength="100">
                    <input type="submit" value="Enviar" id="boton-enviar">
                </form>
            </div>
            <a href="/vehiculos/alta" id="boton-alta">Crear Vehiculo</a>
            <div class="main__contenedor-principal__lista">
                {% for vehiculo in lista_vehiculos %}
                    <ul>
                        <li class="animate__animated animate__flipInX"> Tipo: {{vehiculo.tipo}}, Antiguedad: {{vehiculo.antiguedad}}, Marca: {{vehiculo.marca}} 
                        </li>
                        <a href='/vehiculos/actualizar/{{ vehiculo.id }}'>{% load static %}<img src="{% static 'edit.png' %}" alt=""></a>
                        <a href='/vehiculos/borrar/{{ vehiculo.id }}'>{% load static %}<img src="{% static 'delete.png' %}" alt=""></a>
                    </ul>
                {% endfor %}
            </div>
            {% endblock %}